### ISSUE TITLE
functree2 webpage is not available

### ISSUE THREAD

**Issue by khemlalnirmalkar** [yamada-lab/functree-ng#22] opened 2021-03-11 04:07 UTC
Hi,
I find Functree2 very useful for my datasets but from last one-week webpage is not working,
whenever I upload something it says the page is not available or ajax error.
I am using this site https://bioviz.tokyo/functree2/
Please can you check what wrong with the page or something I need to try,
I will look forward to your response,
Thanks,
Khem

**Comment by omixer** [comment] 2021-03-12 07:50
Hi Khem,

Thank you for reporting this issue! The sysadmin is diagnostic the error, I will let you know as soon as it is back online.

Best,
Youssef

**Comment by khemlalnirmalkar** [comment] 2021-03-12 20:11
Hi @omixer
Thanks for the response. I hope the issue with the page will resolve soon,
I will be waiting,
Best regards,
Khem

**Comment by omixer** [comment] 2021-03-22 02:42
Hi Khem,

Sorry for the delay, the issue is fixed now!
Just in case you are using your own reference tree please don't call it KEGG or the page will break again.
I am implementing constraints on the upload form for reference trees so the problem does not happen again.

Best,
Youssef

**Closed by omixer** 2021-03-22 02:42 UTC
